"""Physics-driven assembly state machine and reproducible trial metrics."""

from dataclasses import asdict, dataclass

import mujoco
import numpy as np

from .control import PoseIK, smoothstep
from .scene import load_model


@dataclass(frozen=True)
class Config:
    seed: int = 0
    randomize: bool = False
    offset_mm: float = 0.0
    force_limit: float = 35.0
    duration: float = 12.0

    def __post_init__(self):
        if not np.isfinite(self.offset_mm) or abs(self.offset_mm) > 30:
            raise ValueError("offset_mm must be finite and between -30 and 30")
        if not np.isfinite(self.force_limit) or self.force_limit <= 0:
            raise ValueError("force_limit must be positive and finite")
        if not np.isfinite(self.duration) or self.duration < 10:
            raise ValueError("duration must be finite and at least 10 seconds")


class AssemblySimulation:
    """Two idealized fixed grasps with actual peg/socket collision dynamics.

    qpos is initialized once on reset. Every subsequent motion is generated by
    bounded position actuators and mj_step, including during contact.
    """

    control_dt = 0.01

    def __init__(self, config: Config | None = None):
        self.config = config or Config()
        self.model = load_model()
        self.data = mujoco.MjData(self.model)
        self.left = PoseIK(self.model, "left", "socket_center")
        self.right = PoseIK(self.model, "right", "peg_tip")
        self.peg_id = self.model.geom("peg").id
        self.socket_geoms = {
            self.model.geom(f"socket_{s}").id for s in ("east", "west", "north", "south")
        }
        self.reset()

    def reset(self):
        mujoco.mj_resetData(self.model, self.data)
        rng = np.random.default_rng(self.config.seed)
        self.goal = np.array([0.0, -0.06, 0.70])
        if self.config.randomize:
            self.goal += rng.uniform([-0.025, -0.02, -0.015], [0.025, 0.02, 0.015])
        self.left_start = self.goal + [-0.16, 0, 0]
        self.right_start = self.goal + [0.16, 0, 0.17]
        self.data.qpos[self.left.qids] = [0, -0.3, 0, 1.3, 0, -1.0, 0]
        self.data.qpos[self.right.qids] = [0, 0.3, 0, -1.3, 0, -2.14, 0]
        self.data.qpos[self.left.qids] = self.left.solve(
            self.data.qpos, self.left_start, iterations=250
        )
        self.data.qpos[self.right.qids] = self.right.solve(
            self.data.qpos, self.right_start, iterations=250
        )
        self.data.ctrl[:] = self.data.qpos
        mujoco.mj_forward(self.model, self.data)
        for site, target in (("socket_center", self.left_start), ("peg_tip", self.right_start)):
            if np.linalg.norm(self.data.site(site).xpos - target) > 0.001:
                raise RuntimeError(f"Initial pose unreachable: {site}")
        self.phase = "SETTLE"
        self.status = "running"
        self.peak_force = 0.0
        self.contact_force = 0.0
        self.contact_steps = 0
        self.hold_time = 0.0
        self.trace = []
        self.steps = 0
        self._record()

    @property
    def done(self):
        return self.status != "running"

    @property
    def progress(self):
        """Fraction of the configured trial duration that has elapsed, in [0, 1]."""
        return float(min(self.data.time / self.config.duration, 1.0))

    def measurements(self):
        socket = self.data.site("socket_center")
        peg = self.data.site("peg_tip")
        rotation = socket.xmat.reshape(3, 3)
        relative = rotation.T @ (peg.xpos - socket.xpos)
        alignment = np.clip(rotation[:, 2] @ peg.xmat.reshape(3, 3)[:, 2], -1, 1)
        return {
            "lateral_error_mm": float(np.linalg.norm(relative[:2]) * 1000),
            "insertion_depth_mm": float((0.025 - relative[2]) * 1000),
            "angle_error_deg": float(np.degrees(np.arccos(alignment))),
            "socket_error_mm": float(np.linalg.norm(socket.xpos - self.goal) * 1000),
        }

    def _targets(self):
        t = self.data.time
        offset = np.array([self.config.offset_mm / 1000, 0.0, 0.0])
        above = self.goal + [0, 0, 0.12] + offset
        if t < 0.75:
            self.phase = "SETTLE"
            return self.left_start, self.right_start
        if t < 3.75:
            self.phase = "TRANSFER"
            fraction = (t - 0.75) / 3
            return (
                smoothstep(self.left_start, self.goal, fraction),
                smoothstep(self.right_start, above, fraction),
            )
        # Track the measured socket after transfer to compensate holder motion.
        socket = self.data.site("socket_center").xpos.copy()
        if t < 5.25:
            self.phase = "ALIGN"
            return self.goal, socket + offset + [0, 0, 0.12]
        if t < 9.25:
            self.phase = "INSERT"
            height = float(smoothstep(0.12, -0.015, (t - 5.25) / 4))
            return self.goal, socket + offset + [0, 0, height]
        self.phase = "HOLD"
        return self.goal, socket + offset + [0, 0, -0.015]

    def step(self):
        if self.done:
            return
        if self.steps % 5 == 0:
            left_target, right_target = self._targets()
            self.data.ctrl[:7] = self.left.solve(self.data.qpos, left_target)
            self.data.ctrl[7:] = self.right.solve(self.data.qpos, right_target)
        mujoco.mj_step(self.model, self.data)
        # Update Cartesian measurements to the newly integrated configuration.
        mujoco.mj_forward(self.model, self.data)
        self.steps += 1
        self.contact_force = 0.0
        for i in range(self.data.ncon):
            contact = self.data.contact[i]
            pair = {int(contact.geom1), int(contact.geom2)}
            if self.peg_id in pair and pair.intersection(self.socket_geoms):
                wrench = np.zeros(6)
                mujoco.mj_contactForce(self.model, self.data, i, wrench)
                self.contact_force += float(np.linalg.norm(wrench[:3]))
        self.peak_force = max(self.peak_force, self.contact_force)
        self.contact_steps += int(self.contact_force > 0.01)
        metrics = self.measurements()
        if not np.all(np.isfinite(self.data.qpos)) or np.any(self.data.warning.number):
            self.status, self.phase = "unstable", "ABORT"
        elif self.contact_force > self.config.force_limit:
            self.status, self.phase = "force_limit", "ABORT"
        elif self.phase == "HOLD":
            valid = (
                metrics["lateral_error_mm"] < 3.0
                and 36 < metrics["insertion_depth_mm"] < 44
                and metrics["angle_error_deg"] < 2
                and metrics["socket_error_mm"] < 3
            )
            self.hold_time = self.hold_time + self.model.opt.timestep if valid else 0.0
            if self.hold_time >= 0.5:
                self.status, self.phase = "success", "COMPLETE"
        if self.data.time >= self.config.duration and not self.done:
            self.status, self.phase = "timeout", "ABORT"
        if self.steps % 10 == 0 or self.done:
            self._record()

    def _record(self):
        self.trace.append(
            {
                "time": float(self.data.time),
                "phase": self.phase,
                "contact_force_n": self.contact_force,
                **self.measurements(),
            }
        )

    def run(self):
        while not self.done:
            self.step()
        return self.result()

    def result(self):
        return {
            "status": self.status,
            "success": self.status == "success",
            "simulation_time_s": float(self.data.time),
            "peak_contact_force_n": self.peak_force,
            "contact_steps": self.contact_steps,
            "stable_hold_s": self.hold_time,
            **self.measurements(),
            "config": asdict(self.config),
        }
